/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:1b0139f7-2b0c-4896-9f2e-1647baf77e05",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_g6hckmPph",
    "aws_user_pools_web_client_id": "13i439rcb0abs0e1ui9gupl698",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://3uiyio55yfbvtnmftd4e2zmi6y.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "AWS_IAM",
    "aws_user_files_s3_bucket": "rheastagram78ee021367fa4048b077007dac4021f9124335-rheaenvone",
    "aws_user_files_s3_bucket_region": "us-east-1"
};


export default awsmobile;
